config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  scope "/admin" do
    resources :users
  end
  resources :bookings
  resources :statuses

  root :to => 'welcome#index'

  authenticated :user  do
    root to: "bookings#index" , as: :user_root
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
    else
      can :read, Booking
      can :create, Booking
      # can :update, Booking do |session|
      #   session.try(:user) == user
      # end
      can :destroy, Booking do |sess|
        sess.try(:user) == user
      end

    end
  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
has_one :user
has_one :status

  validates :room_number, presence: true
  validates :user_id, presence: true
  validates_datetime :session_start, :after => :now, uniqueness: true
  validates_datetime :session_end, :on_or_before => :_later, uniqueness: true
  validate :end_time_is_after_start_time
  validates_time :session_start , :between => ['9:00am', '21:00pm']
  validates_time :session_end , :between => ['9:00am', '21:00pm']
  validate :week_end
# before_save :booked_session
#
# def booked_session
#   @book = Booking.where(:session_start => self.session_start.to_date)
#   if @book[:session_start] > self.session_start  && self.session_start < @book[:session_end]
#     errors.add(:session_start,"This Session is already booked")
#   end
# end

  def _later
    self.session_start + 2.hour + 45.minute
  end
  def end_time_is_after_start_time
    return if session_end.blank? || session_start.blank?

    if session_end < session_start
      errors.add(:session_end, "cannot be before the start time")
    end

  end
  def week_end
    if session_start.saturday? || session_start.sunday?
      errors.add(:session_start,"We are close on week ends")
    end
  end

end

app/models/status.rb
class Status < ActiveRecord::Base
belongs_to :booking
end

app/models/user.rb
class User < ActiveRecord::Base
belongs_to :booking
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :band_name, presence: true
  validates :contact_name , presence: true
  validates :phone_number , presence: true

  before_save :assign_user_role


  def assign_user_role
    self.is_admin = 0
  end
def admin?
  self.is_admin == 1
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :band_name
    devise_parameter_sanitizer.for(:sign_up) << :contact_name
    devise_parameter_sanitizer.for(:sign_up) << :phone_number

    devise_parameter_sanitizer.for(:account_update) << :band_name
    devise_parameter_sanitizer.for(:account_update) << :contact_name
    devise_parameter_sanitizer.for(:account_update) << :phone_number
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  before_action :set_booking, only: [:show, :edit, :update, :destroy]




  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    # @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id
    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:room_number, :user_id, :session_start, :session_end, :session_count, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @joined_on = @user.created_at.to_formatted_s(:short)
    if @user.current_sign_in_at
      @last_login = @user.current_sign_in_at.to_formatted_s(:short)
    else
      @last_login = "never"
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if user_params[:password].blank?
      user_params.delete(:password)
      user_params.delete(:password_confirmation)
    end

    successfully_updated = if needs_password?(@user, user_params)
                             @user.update(user_params)
                           else
                             @user.update_without_password(user_params)
                           end

    respond_to do |format|
      if successfully_updated
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  protected
  def needs_password?(user, params)
    params[:password].present?
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:band_name, :contact_name, :phone_number,:email, :password, :password_confirmation,:is_admin )
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room_number %><br>
    <%= f.number_field :room_number %>
  </div>

  <div class="field">
    <%= f.label :session_start %><br>
    <%= f.datetime_select :session_start %>
  </div>
  <div class="field">
    <%= f.label :session_end %><br>
    <%= f.datetime_select :session_end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Room number</th>
      <th>Session start</th>
      <th>Session end</th>
      <th>Session count</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.room_number %></td>

        <td><%= booking.session_start %></td>
        <td><%= booking.session_end %></td>
        <td><% if can? :read, booking %>
          <%= link_to 'Show', booking %>
          <% end %>
        </td>

        <td><% if can? :update, booking %>
          <%= link_to 'Edit', edit_booking_path(booking) %>
          <% end %></td>

        <td><% if can? :destroy, booking %>
          <%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room number:</strong>
  <%= @booking.room_number %>
</p>


<p>
  <strong>Session start:</strong>
  <%= @booking.session_start %>
</p>

<p>
  <strong>Session end:</strong>
  <%= @booking.session_end %>
</p>




<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecordingStudio</title>
  <%= stylesheet_link_tag    '', media: 'all'  %>
  <%= javascript_include_tag '' %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Edit profile", edit_user_registration_path %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
<% end %>

<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :band_name %><br>
    <%= f.text_field :band_name %>
  </div>
  <div class="field">
    <%= f.label :contact_name %><br>
    <%= f.text_field :contact_name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password, placeholder: "Leave blank if unchanged" %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Band name</th>
      <th>Contact name</th>
      <th>Phone number</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.band_name %></td>
        <td><%= user.contact_name %></td>
        <td><%= user.phone_number %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Band name:</strong>
  <%= @user.band_name %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @user.contact_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @user.phone_number %>
</p>

<p>
  <strong>Email:</strong>
    <%= @user.email %>
</p>
<p>
  <strong>Joined on:</strong>
  <%= @joined_on %>
</p>
<p>
  <strong>Last logged in on:</strong>
  <%= @last_login %>
</p>
<p>
  <strong>No. times logged in:</strong>
  <%= @user.sign_in_count %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Welcome to Romeo recording Studio</h1>
<p>please singup if you are new user.</p>